name: 焦灿的技术博客
description: 我是一名水笔程序猿
meta_description: “我是一名水笔程序猿”

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         '焦灿'
